package HireCraft.com.SpringBoot.enums;

public enum NotificationType {
    MESSAGE,
    NEW_BOOKING_REQUEST,
    BOOKING_REMINDER,
    PAYMENT_RECEIVED,
    REVIEW_RECEIVED,
    BOOKING_ACCEPTED,
    BOOKING_DECLINED,
    BOOKING_COMPLETED,
    BOOKING_CANCELLED,
    SYSTEM_ANNOUNCEMENT,
    PROFILE_UPDATE,
    GENERAL
}
