-- V2__add_city_state_country_to_users.sql

ALTER TABLE users ADD COLUMN country VARCHAR(100) NOT NULL DEFAULT 'Nigeria';
ALTER TABLE users ADD COLUMN state VARCHAR(100) NOT NULL DEFAULT 'Lagos';
ALTER TABLE users ADD COLUMN city VARCHAR(100) NOT NULL DEFAULT 'Ikeja';

--ALTER TABLE users ADD COLUMN country VARCHAR(100) NOT NULL;
--ALTER TABLE users ADD COLUMN state VARCHAR(100) NOT NULL;
--ALTER TABLE users ADD COLUMN city VARCHAR(100) NOT NULL;